{
 "title": "Device Overview",
 "tags": [
  "Device",
  "Kafka",
  "High Level"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "total_dev", "query": "${VAR_TOTAL_DEV}" }
  ]
 },
 "panels": [
  {
   "title": "Avail %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"admin_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"device_status\" and\n    r._field == \"bypass\"\n  )\n  |> last()\n  |> group()\n  |> count()\n  |> map(fn: (r) => ({\n      _value: float(v: r._value) / float(v: ${total_dev}) * 100.0,\n      _measurement: \"bypass_percentage\"\n  }))"
    }
   ]
  },
  {
   "title": "Bypass %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bypass =\n  from(bucket: \"admin_bucket\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n      r._measurement == \"device_status\" and\n      r._field == \"bypass\" and\n      r._value == true\n    )\n    |> last()\n    |> group()\n    |> count()\n    |> map(fn: (r) => ({ r with join_key: \"all\" }))\n\ntotal =\n  from(bucket: \"admin_bucket\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n      r._measurement == \"device_status\" and\n      r._field == \"bypass\"\n    )\n    |> last()\n    |> group()\n    |> count()\n    |> map(fn: (r) => ({ r with join_key: \"all\" }))\n\njoin(\n  tables: {bypass: bypass, total: total},\n  on: [\"join_key\"]\n)\n|> map(fn: (r) => ({\n  _value: float(v: r._value_bypass) / float(v: r._value_total) * 100.0,\n  _measurement: \"bypass_percentage\"\n}))"
    }
   ]
  },
  {
   "title": "Bypass Status by Device",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"admin_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"device_status\" and\n    r._field == \"bypass\"\n  )"
    }
   ]
  }
 ]
}